# Generated by Django 4.2.6 on 2023-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_translations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categorytranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="categorytranslation",
            name="master",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="shop_catego_name_289c7e_idx"),
        ),
        migrations.DeleteModel(
            name="CategoryTranslation",
        ),
    ]
